database {
  profile = "slick.jdbc.HsqldbProfile$"
  db {
    driver = "org.hsqldb.jdbcDriver"
    url = "jdbc:hsqldb:file:conf/cromwell/cromwell-db;shutdown=false"
    connectionTimeout = 5000
  }
}

call-caching {
  enabled = true
}
